// Code generated by protoc-gen-go.
// source: event.proto
// DO NOT EDIT!

/*
Package event is a generated protocol buffer package.

It is generated from these files:
	event.proto

It has these top-level messages:
	Event
	EventThingStarted
*/
package event

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EventThingStarted_ThingTypes int32

const (
	EventThingStarted_THING_ONE EventThingStarted_ThingTypes = 0
	EventThingStarted_THING_TWO EventThingStarted_ThingTypes = 1
)

var EventThingStarted_ThingTypes_name = map[int32]string{
	0: "THING_ONE",
	1: "THING_TWO",
}
var EventThingStarted_ThingTypes_value = map[string]int32{
	"THING_ONE": 0,
	"THING_TWO": 1,
}

func (x EventThingStarted_ThingTypes) String() string {
	return proto.EnumName(EventThingStarted_ThingTypes_name, int32(x))
}
func (EventThingStarted_ThingTypes) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

type Event struct {
	Id      int32                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Payload *google_protobuf.Any `protobuf:"bytes,2,opt,name=payload" json:"payload,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Event) GetPayload() *google_protobuf.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

type EventThingStarted struct {
	Type EventThingStarted_ThingTypes `protobuf:"varint,1,opt,name=type,enum=event.EventThingStarted_ThingTypes" json:"type,omitempty"`
	Name string                       `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *EventThingStarted) Reset()                    { *m = EventThingStarted{} }
func (m *EventThingStarted) String() string            { return proto.CompactTextString(m) }
func (*EventThingStarted) ProtoMessage()               {}
func (*EventThingStarted) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*Event)(nil), "event.Event")
	proto.RegisterType((*EventThingStarted)(nil), "event.EventThingStarted")
	proto.RegisterEnum("event.EventThingStarted_ThingTypes", EventThingStarted_ThingTypes_name, EventThingStarted_ThingTypes_value)
}

func init() { proto.RegisterFile("event.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x2d, 0x4b, 0xcd,
	0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0xa4, 0x24, 0xd3, 0xf3, 0xf3,
	0xd3, 0x73, 0x52, 0xf5, 0xc1, 0x82, 0x49, 0xa5, 0x69, 0xfa, 0x89, 0x79, 0x95, 0x10, 0x15, 0x4a,
	0xee, 0x5c, 0xac, 0xae, 0x20, 0x35, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0xac, 0x41, 0x4c, 0x99, 0x29, 0x42, 0x7a, 0x5c, 0xec, 0x05, 0x89, 0x95, 0x39, 0xf9, 0x89,
	0x29, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0x22, 0x7a, 0x10, 0x53, 0xf4, 0x60, 0xa6, 0xe8,
	0x39, 0xe6, 0x55, 0x06, 0xc1, 0x14, 0x29, 0xf5, 0x30, 0x72, 0x09, 0x82, 0x4d, 0x0a, 0xc9, 0xc8,
	0xcc, 0x4b, 0x0f, 0x2e, 0x49, 0x2c, 0x2a, 0x49, 0x4d, 0x11, 0x32, 0xe7, 0x62, 0x29, 0xa9, 0x2c,
	0x48, 0x05, 0x9b, 0xcb, 0x67, 0xa4, 0xac, 0x07, 0x71, 0x1c, 0x86, 0x3a, 0x3d, 0x30, 0x27, 0xa4,
	0xb2, 0x20, 0xb5, 0x38, 0x08, 0xac, 0x41, 0x48, 0x88, 0x8b, 0x25, 0x2f, 0x31, 0x37, 0x15, 0x6c,
	0x37, 0x67, 0x10, 0x98, 0xad, 0xa4, 0xc5, 0xc5, 0x85, 0x50, 0x27, 0xc4, 0xcb, 0xc5, 0x19, 0xe2,
	0xe1, 0xe9, 0xe7, 0x1e, 0xef, 0xef, 0xe7, 0x2a, 0xc0, 0x80, 0xe0, 0x86, 0x84, 0xfb, 0x0b, 0x30,
	0x26, 0xb1, 0x81, 0x5d, 0x69, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x8a, 0x76, 0x98, 0x0f,
	0x01, 0x00, 0x00,
}
